### ISSUE TITLE
Drop PHP requirement

### ISSUE THREAD

**Issue by michaelarnauts** [cgarwood/hacontrolpoint#5]
Since you can whitelist IP addresses in HA so they don't have to login, you can drop the PHP proxy in between. This makes it more secure, since the proxy is reachable by everyone, and the API itself only from the device that is running the frontend. An added bonus is a small speed increase because you can directly connect to Home Assistant.

I have this in my `configuration.yaml` of HA:

```yaml
  trusted_networks:
    - 192.168.1.0/24
  cors_allowed_origins:
    - 'null'
    - '*'
```

The `cors_allowed_origins` is needed because Chrome doesn't like AJAX calls when the index.html is opened locally (it might be that this is only during testing when the index.html is opened in a browser).
